{
 "title": "Projet-cloud",
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\") |> range(start: -1m) |> filter(fn: (r) => r._measurement == \"cpu\" and r._field == \"usage\")"
    }
   ]
  },
  {
   "title": "Température Capteur",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\") |> range(start: -10m) |> filter(fn: (r) => r._measurement == \"temperature\" and r._field == \"value\")"
    }
   ]
  },
  {
   "title": "Taux d'erreur",
   "type": "stat",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\") |> range(start: -5m) |> filter(fn: (r) => r._measurement == \"error_rate\" and r._field == \"value\")"
    }
   ]
  },
  {
   "title": "Métrique Simulée",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 6 },
   "targets": [
    {
     "query": "from(bucket: \"mybucket\") |> range(start: -10m) |> filter(fn: (r) => r._measurement == \"metric\" and r._field == \"value\")"
    }
   ]
  }
 ]
}